### ISSUE TITLE
Menu options break on mobile screens

### ISSUE THREAD

**Issue by ereslibre** [rancherlabs/projects-theme#4]
Given a menu of options, on the `config.toml` configuration, like:

```toml
[menu]

  [[menu.main]]
    identifier = "hub"
    name = "Policy Hub"
    url = "https://hub.kubewarden.io/"
    weight = -130

  [[menu.main]]
    identifier = "charts"
    name = "Helm Charts"
    url = "https://charts.kubewarden.io/"
    weight = -120

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "https://docs.kubewarden.io/"
    weight = -110
```

On a regular screen, the contents look fine:

![Screenshot from 2021-04-21 13-36-00](https://user-images.githubusercontent.com/8706/115547554-af0bf780-a2a6-11eb-9812-ec010a2f9b37.png)

However, on a smaller screen, we see that the menu items: Policy Hub and Helm Charts seem to overflow on top of themselves:

![Screenshot from 2021-04-21 13-36-30](https://user-images.githubusercontent.com/8706/115547649-cb0f9900-a2a6-11eb-8b88-963ada363b41.png)

On very small displays (on the sample, iPhone 5), the main content is also not filling the whole content viewport:

![Screenshot from 2021-04-21 13-36-51](https://user-images.githubusercontent.com/8706/115547705-dcf13c00-a2a6-11eb-94d9-e7c17f15ca95.png)

The way we have fixed the top menu mobile appearance, at least until we have a good solution is by using this patch in our website:

```diff
commit 5197242aeef1641be9ec5f80045ae672a0ba4e28
Author: Rafael Fernández López <ereslibre@ereslibre.es>
Date:   Wed Apr 21 10:45:29 2021 +0200

    Make menu look fine on narrow displays

diff --git a/assets/sass/main.scss b/assets/sass/main.scss
index 46a1cfe..b955448 100644
--- a/assets/sass/main.scss
+++ b/assets/sass/main.scss
@@ -7,6 +7,20 @@
     --light           : #F3F3F3;
   }
 
+  .sub-header {
+    white-space: nowrap;
+    flex-flow: wrap;
+  }
+
+  .sub-header ul {
+    display: flex;
+    flex-flow: wrap;
+  }
+
+  .sub-header ul li {
+    display: block;
+  }
+
   .navbar-brand {
     flex: 1;
   }
```

This solution is very probably suboptimal, given we are not designers, but it does the job until we have a proper fix.

Thank you.
